### ISSUE TITLE
There is no "_StartGame.bat" included in the repository

### ISSUE THREAD

**Issue by squaredx** [SebastianMalek/blaze-server#4]
Hey, I was just testing out this blaze server emulator, but I am unable to test client connection as there is no _StartGame.bat. Nice work by the way!

**Comment by SebastianMalek** [comment]
I'm going to update it today.

**Comment by SebastianMalek** [comment]
Updated. Let me know if you have any issues. Currently, you won't be able to play with more players but you can test the game locally.
